# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 906f1522a0fb8b766ae0eae5c63b25434e46b564851c6a547aaf4391a4b313629fc423c798b0ea9753f88e4b9e39dcc3b48d254f339549d09081e99beeac3d05

test:
  secret_key_base: b46625ac451664b0e882b8bb77f3f65df48ec163ff32ea8237ecf1aa18df16fa0b7b866ae670a9b75d8558508a498989f52f4abf0cc084f08ddbf8bc14e72a5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
